''
'' A gray and yellow theme based on the SierraHOTAS color scheme
''
'' Author: Joe Kolodz
'' Copyright (c) 2022 by Joe kOlodz
!$THEME = "sierrahotas"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

'color definitions - do not use these directly
!$BLACK = "#000"
!$GOLD = "#ffd700"
!$AZURE = "#f0ffff"
!$RED = "#f00"
!$GREEN = "#7cfc00"
!$BRIGHT_BLUE = "#80e5ff"

''text header
!$LIGHT_BLUE = "#7ac1ff"
''selected border
!$MEDIUM_BLUE = "#26a0da"
''hover
!$DARK_BLUE = "#2a7aa1"
''group border
!$SLATEGRAY = "#708090"

''alternate row
!$MEDIUM_GRAY = "#424242"
''window background
!$DARK_GRAY = "#323232"

''hover border
!$LIGHT_BLUEGRAY = "#2a7aa1"
''selected
!$MEDIUM_BLUEGRAY = "#2f4c5a"
''hover
!$DARK_BLUEGRAY = "#313f47"

'definitions for color usages, do not use # values here for colors. define them above first
!$BACKGROUND = $DARK_GRAY
!$HEADER_TEXT = $LIGHT_BLUE
!$TEXT = $AZURE
!$ERROR = $RED
!$HEADER_BACKGROUND = $DARK_BLUEGRAY
!$OBJECT_BACKGROUND = $MEDIUM_GRAY
!$OBJECT_BORDER = $SLATEGRAY
!$START = $GREEN
!$END = $RED
!$ARROW_COLOR = $GOLD

'Title
!$TITLE_TEXT = $GOLD

'Sequence
!$LIFE_LINE_BACKGROUND = $GOLD
!$LIFE_LINE_BORDER = $MEDIUM_BLUE
!$GROUP_BORDER = $DARK_BLUE
!$DIVIDER_TEXT = $GOLD
!$REFERENCE_TEXT = $DARK_BLUEGRAY
!$STEREOTYPE_TEXT = $GREEN

'Note
!$NOTE_TEXT = $GOLD
!$NOTE_BORDER = $GOLD
!$NOTE_BACKGROUND = $BLACK


!procedure $primary_scheme()
    FontColor $TEXT
    BorderColor $OBJECT_BORDER
    BackgroundColor $OBJECT_BACKGROUND
!endprocedure

!procedure $secondary_scheme()
    FontColor $HEADER_TEXT
    BorderColor $OBJECT_BORDER
    BackgroundColor $HEADER_BACKGROUND
!endprocedure

skinparam BackgroundColor       $BACKGROUND
skinparam useBetaStyle          false
skinparam defaultFontName       "Arial"
skinparam defaultFontSize       14
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           6
skinparam ParticipantPadding    30
skinparam BoxPadding            40
skinparam Padding               1

!startsub stereotype

skinparam stereotype {
    'Class and Entity
    CBackgroundColor $GREEN
    CBorderColor $MEDIUM_GRAY

    'Abstract and Abstract Class
    ABackgroundColor $MEDIUM_BLUE
    ABorderColor $MEDIUM_GRAY

    'Interface
    IBackgroundColor $GOLD
    IBorderColor $MEDIUM_GRAY

    'Enum
    EBackgroundColor $BRIGHT_BLUE
    EBorderColor $MEDIUM_GRAY

    'Annotation
    NBackgroundColor $BRIGHT_BLUE
    NBorderColor $MEDIUM_GRAY
}

!endsub

!startsub title

skinparam title {
    $primary_scheme()
    FontColor $TITLE_TEXT
}

!endsub

!startsub legend

skinparam legend {
    BackgroundColor $OBJECT_BACKGROUND
    BorderColor $OBJECT_BORDER
    FontColor $TEXT
}

!endsub


!startsub person

skinparam person {
    $secondary_scheme()
}

!endsub

!startsub swimlane

skinparam swimlane {
    $primary_scheme()
}

!endsub

!startsub activity

skinparam activity {
    FontColor $TEXT
    BorderColor $OBJECT_BORDER
    BackgroundColor $OBJECT_BACKGROUND
    BarColor $HEADER_TEXT
    StartColor $START
    EndColor $END
    DiamondBackgroundColor $HEADER_BACKGROUND
    DiamondBorderColor $OBJECT_BORDER
    DiamondFontColor $TEXT
}

!endsub

!startsub participant

skinparam participant {
    $primary_scheme()
    ParticipantBorderThickness 2
}
!endsub

!startsub actor

skinparam actor {
    $primary_scheme()
}
!endsub

!startsub arrow

skinparam arrow {
    Thickness 1
    Color $ARROW_COLOR
    FontColor $TEXT
}

!endsub

!startsub sequence

skinparam sequence {
	BoxBackgroundColor $HEADER_BACKGROUND
	BoxBorderColor $HEADER_TEXT
	BoxFontColor $HEADER_TEXT
	''
	DelayFontColor $TEXT
	''
	LifeLineBorderColor $LIFE_LINE_BORDER
	LifeLineBorderThickness 2
	LifeLineBackgroundColor $LIFE_LINE_BACKGROUND
	''
	GroupBorderColor $GROUP_BORDER
	GroupFontColor $TEXT
	GroupHeaderFontColor $HEADER_TEXT
	GroupBackgroundColor $HEADER_BACKGROUND
	GroupBodyBackgroundColor $OBJECT_BACKGROUND
	GroupHeaderBackgroundColor $BACKGROUND
	''
	DividerBackgroundColor $OBJECT_BACKGROUND
    DividerBorderColor $OBJECT_BORDER
    DividerBorderThickness 2
    DividerFontColor $DIVIDER_TEXT
	''
	ReferenceBackgroundColor $OBJECT_BACKGROUND
	ReferenceBorderColor $OBJECT_BORDER
	ReferenceFontColor $REFERENCE_TEXT
	ReferenceHeaderFontColor $HEADER_TEXT
	''
	StereotypeFontColor $STEREOTYPE_TEXT
    ''
	AttributeFontColor $TEXT
	AttributeFontSize 50
}
!endsub

!startsub partition

skinparam partition {
    BackgroundColor $HEADER_BACKGROUND
}
!endsub

!startsub collections

skinparam collections {
    $primary_scheme()
}
!endsub

!startsub control

skinparam control {
    $primary_scheme()
}
!endsub

!startsub entity

skinparam entity {
    $primary_scheme()
}
!endsub

!startsub boundary

skinparam boundary {
    $primary_scheme()
}
!endsub

!startsub agent

skinparam agent {
    $primary_scheme()
}
!endsub

!startsub note

skinparam note {
    FontColor $NOTE_TEXT
    BorderColor $NOTE_BORDER
    BackgroundColor $NOTE_BACKGROUND
}

!endsub

!startsub artifact

skinparam artifact {
    $primary_scheme()
}
!endsub

!startsub component

skinparam component {
    $primary_scheme()
}
!endsub

!startsub interface

skinparam interface {
    $primary_scheme()
}
!endsub

!startsub storage

skinparam storage {
    $primary_scheme()
}
!endsub

!startsub node

skinparam node {
    $primary_scheme()
}
!endsub

!startsub cloud

skinparam cloud {
    $secondary_scheme()
    BorderColor $HEADER_TEXT
}
!endsub

!startsub database

skinparam database {
    $primary_scheme()
}
!endsub

!startsub class

skinparam class{
    $primary_scheme()

    HeaderBackgroundColor $HEADER_BACKGROUND
    StereotypeFontColor $TEXT
    FontSize 14
    BorderThickness 1
    AttributeFontColor $TEXT
    AttributeFontSize 14
}

!endsub

!startsub object

skinparam object {
    $primary_scheme()
    StereotypeFontColor $TEXT
    BorderThickness 1
    AttributeFontColor $TEXT
    AttributeFontSize 11
}
!endsub

!startsub usecase

skinparam usecase {
    $primary_scheme()
    BorderThickness 1
    StereotypeFontColor $TEXT
}
!endsub

!startsub hexagon

skinparam hexagon {
    $primary_scheme()
}

!endsub

!startsub rectangle

skinparam rectangle {
    $primary_scheme()
    BorderThickness 1
    StereotypeFontColor $TEXT
}
!endsub

!startsub package

'The Activity diagram's partition uses package's BorderColor, FontColor, and Thickness, but not BackgroundColor
skinparam package {
    $secondary_scheme()
    StereotypeFontColor $TEXT
    BorderThickness 2
}

!endsub

!startsub folder

skinparam folder {
    $secondary_scheme()
}
!endsub

!startsub frame

skinparam frame {
    $secondary_scheme()
}
!endsub

!startsub state

skinparam state {
    $primary_scheme()
    StartColor $START
    EndColor $END
    AttributeFontColor $TEXT
    AttributeFontSize 11
}
!endsub

!startsub queue

skinparam queue {
    $primary_scheme()
}
!endsub

!startsub card

skinparam card {
    $primary_scheme()
}
!endsub

!startsub file

skinparam file {
    $primary_scheme()
}
!endsub

!startsub stack

skinparam stack {
    $primary_scheme()
}
!endsub
